### ISSUE TITLE
Tiktok music url resolution failed

### ISSUE THREAD

**Issue by instaer** [yi005/Tiktok-Video-No-Watermark#3]
When a video url is passed in, the music url will be returned, but when a music url like [https://vm.tiktok.com/ZM8cX6YXY/](https://vm.tiktok.com/ZM8cX6YXY/) is passed in, the resolution  fails.

**Comment by yi005** [comment]
This is normal. For the music url, I will provide a separate API to get list.

**Comment by yi005** [comment]
> 传入视频url时，会返回音乐url，但传入https://vm.tiktok.com/ZM8cX6YXY/等音乐url时，解析失败。

You want music detail or video list?

**Comment by yi005** [comment]
Now supported.

https://www.tikwm.com/api/music/posts?music_id=6788770563495185158&count=10&cursor=0

**Comment by instaer** [comment]
> Now supported.
> 
> https://www.tikwm.com/api/music/posts?music_id=6788770563495185158&count=10&cursor=0

Thanks for your support! At present, I just need to download music through tiktok music url. As for downloading video list through music id, I think it should be useful, even if I don’t use it yet.

**Comment by yi005** [comment]
> > 现在支持。
> > https://www.tikwm.com/api/music/posts?music_id=6788770563495185158&count=10&cursor=0
> 
> 谢谢你的支持！目前我只需要通过抖音音乐网址下载音乐即可。至于通过音乐id下载视频列表，我觉得应该还是有用的，虽然我还没用过。

好的，会尽快增加一个音乐详情解析接口

**Comment by yi005** [comment]
> When a video url is passed in, the music url will be returned, but when a music url like https://vm.tiktok.com/ZM8cX6YXY/ is passed in, the resolution fails.

You can use the music details analysis interface to get the detailed content of the music, including the play url.

Example: https://www.tikwm.com/api/music/info?url=https%3A%2F%2Fvm.tiktok.com%2FZM8cX6YXY%2F

**Comment by instaer** [comment]
very userful!
