### ISSUE TITLE
Want to know in which case the api always returns HD video?

### ISSUE THREAD

**Issue by instaer** [yi005/Tiktok-Video-No-Watermark#4]
In what case, the api (even add parameter hd=1) always returns HD video, I tried some tiktok links, but compared with no hd parameter (hd=0), the video size is the same.

**Comment by yi005** [comment]
> In what case, the api (even add parameter hd=1) always returns HD video, I tried some tiktok links, but compared with no hd parameter (hd=0), the video size is the same.

I guess this may be related to the original video uploaded by the user.
Can you give me some links to test?

**Comment by yi005** [comment]
By the way, HD video is in data.hdplay field. I hope you're not mistaken.

**Comment by instaer** [comment]
> 

well i have seen that, thanks
