### ISSUE TITLE
Any privacy commitments?

### ISSUE THREAD

**Issue by MinePlayersPE** [yi005/Tiktok-Video-No-Watermark#7]
Not saying _I_ will do this, but I'm pretty sure people _will_ eventually try to use the signer API with their account tokens atleast once :P

**Comment by yi005** [comment]
The ability to make requests with your own cookie already exists, you can add the request header "proxy-cookie" to make requests with your own account token.

But this is not recommended as it is not clear if TT will block the account for this.

**Comment by digustingstan** [comment]
Is "sid_tt" the correct cookie? I cant get it to work with a private account i follow no matter what

**Comment by yi005** [comment]
> Is "sid_tt" the correct cookie? I cant get it to work with a private account i follow no matter what

`sessionid` or `sessionid_ss`

**Comment by digustingstan** [comment]
![image](https://user-images.githubusercontent.com/95265327/198496842-48b8ef43-3949-4bb5-941f-1ba52828413d.png)
Like this? It doesn't work..
Also i can't get the next page of user feed. Please help
