### ISSUE TITLE
Cant load next page

### ISSUE THREAD

**Issue by digustingstan** [yi005/Tiktok-Video-No-Watermark#9]
cursor param doesn't do anything, it's the same life of videos with every request
![image](https://user-images.githubusercontent.com/95265327/198182949-c416707a-1f31-4403-abb8-2a3afa4b29d1.png)

**Comment by yi005** [comment]
fixed

**Comment by digustingstan** [comment]
It still gives me the same list of videos

**Comment by yi005** [comment]
> 

The cursor needs to be obtained from the last request return.

**Comment by digustingstan** [comment]
Thank you so much it works
